# Generated by Django 6.0.3 on 2026-03-25 17:16

import submissions.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "folder_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "nome_projecto",
                    models.CharField(
                        blank=True,
                        help_text="Opcional, mas recomendável.",
                        max_length=200,
                        verbose_name="Nome do projecto",
                    ),
                ),
                (
                    "nome_responsavel",
                    models.CharField(
                        max_length=200, verbose_name="Nome do estudante responsável"
                    ),
                ),
                (
                    "membros_grupo",
                    models.TextField(
                        help_text="Um por linha ou separados por vírgulas.",
                        verbose_name="Membros do grupo",
                    ),
                ),
                (
                    "classe",
                    models.CharField(
                        choices=[("10", "10.º ano"), ("11", "11.º ano")], max_length=2
                    ),
                ),
                (
                    "turma",
                    models.CharField(
                        choices=[
                            ("IF", "IF"),
                            ("ID", "ID"),
                            ("IB", "IB"),
                            ("IG", "IG"),
                        ],
                        max_length=2,
                    ),
                ),
                ("sala", models.CharField(max_length=50, verbose_name="Sala")),
                (
                    "ficheiro_projecto",
                    models.FileField(
                        help_text="Ficheiro ZIP com HTML, CSS e opcionalmente JS.",
                        upload_to=submissions.models.upload_project_zip,
                        verbose_name="Projecto (.zip)",
                    ),
                ),
                (
                    "ficheiro_ata",
                    models.FileField(
                        help_text="PDF com a ata e descrição do projecto.",
                        upload_to=submissions.models.upload_ata_pdf,
                        verbose_name="Ata em PDF",
                    ),
                ),
                ("data_submissao", models.DateTimeField(auto_now_add=True)),
                (
                    "nota",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Para uso futuro na avaliação.",
                        max_digits=4,
                        null=True,
                        verbose_name="Nota",
                    ),
                ),
            ],
            options={
                "verbose_name": "submissão de projecto",
                "verbose_name_plural": "submissões de projectos",
                "ordering": ["-data_submissao"],
            },
        ),
    ]
