# Generated by Django 6.0.3 on 2026-05-31 17:39

import submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0002_sala_select_1_14"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectsubmission",
            name="classe",
            field=models.CharField(
                choices=[("10", "10ª classe"), ("11", "11ª classe")], max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="projectsubmission",
            name="ficheiro_ata",
            field=models.FileField(
                blank=True,
                help_text="PDF com a ata e descrição do projecto.",
                null=True,
                upload_to=submissions.models.upload_ata_pdf,
                verbose_name="Ata em PDF",
            ),
        ),
    ]
