# Generated by Django 6.0.3 on 2026-05-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0003_ficheiro_ata_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectsubmission",
            name="membros_grupo",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Um por linha ou separados por vírgulas.",
                verbose_name="Membros do grupo",
            ),
        ),
    ]
